apiVersion: v1
kind: Service
metadata:
  name: tasks-db-service
  labels:
    app: tasks-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  selector:
    app: tasks-db