apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  JWT_SECRET: OTljNzY2ZWQyYTEyZTU2YmVkODNhYTkxMzVmYzY3MTQ2NTQxZTBjMjc0ZWI3NDFhNWExZWNmNDVjYmI1ZDk1NAo=
  DB_PASSWORD: YXV0aF9wYXNz
