# Tasks Service Secrets
# WARNING: This file contains example secrets for demonstration only!
# DO NOT commit real secrets to git in production.
#
apiVersion: v1
kind: Secret
metadata:
  name: tasks-secrets
type: Opaque
data:
  JWT_SECRET: OTljNzY2ZWQyYTEyZTU2YmVkODNhYTkxMzVmYzY3MTQ2NTQxZTBjMjc0ZWI3NDFhNWExZWNmNDVjYmI1ZDk1NAo=
  DB_PASSWORD: dGFza3NfcGFzcw==