apiVersion: v1
kind: Service
metadata:
  name: tasks-service
  labels:
    app: tasks
spec:
  type: ClusterIP  #
  selector:
    app: tasks
  ports:
  - port: 3002      
    targetPort: 3002
    name: http
